// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ismission12ISGang.Models;

namespace ismission12ISGang.Migrations
{
    [DbContext(typeof(TimeContext))]
    [Migration("20220321214516_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21");

            modelBuilder.Entity("ismission12ISGang.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonID");

                    b.ToTable("persons");

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            Email = "test@test.com",
                            Name = "Jacob Poor",
                            Phone = "800 867 5309",
                            Size = 4
                        });
                });

            modelBuilder.Entity("ismission12ISGang.Models.Time", b =>
                {
                    b.Property<int>("TimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeOfDay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("bReserved")
                        .HasColumnType("INTEGER");

                    b.HasKey("TimeID");

                    b.HasIndex("PersonID");

                    b.ToTable("times");

                    b.HasData(
                        new
                        {
                            TimeID = 1,
                            Day = 12,
                            Month = "March",
                            PersonID = 1,
                            TimeOfDay = "8:00",
                            Year = 2022,
                            bReserved = true
                        },
                        new
                        {
                            TimeID = 2,
                            Day = 12,
                            Month = "March",
                            TimeOfDay = "8:30",
                            Year = 2022,
                            bReserved = false
                        },
                        new
                        {
                            TimeID = 3,
                            Day = 18,
                            Month = "March",
                            TimeOfDay = "8:00",
                            Year = 2022,
                            bReserved = false
                        },
                        new
                        {
                            TimeID = 4,
                            Day = 1,
                            Month = "April",
                            TimeOfDay = "8:00",
                            Year = 2022,
                            bReserved = false
                        },
                        new
                        {
                            TimeID = 5,
                            Day = 1,
                            Month = "April",
                            TimeOfDay = "8:30",
                            Year = 2022,
                            bReserved = false
                        },
                        new
                        {
                            TimeID = 6,
                            Day = 1,
                            Month = "April",
                            TimeOfDay = "9:00",
                            Year = 2022,
                            bReserved = false
                        });
                });

            modelBuilder.Entity("ismission12ISGang.Models.Time", b =>
                {
                    b.HasOne("ismission12ISGang.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID");
                });
#pragma warning restore 612, 618
        }
    }
}
